version: "3.4"

services:
    web:    
        build: .
        command: python frontend/manage.py startserver
        container_name: web
        restart: always
        ports:
            - 5510:5510
        depends_on:
            - db
        environment:
            - RUNNING_DOCKER=1
        networks:
            - crowdeye-ai-engine_some-net


    
    db:
        container_name: postgres
        image: postgres
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        networks:
            - crowdeye-ai-engine_some-net



    influxdb:
        image: influxdb
        container_name: influxdb
        restart: always
        ports:
            - 8086:8086
            - "25826:25826/udp"
        volumes:
            - ./influxdata:/var/lib/influxdb
            - ./config:/etc/influxdb/
        environment:
            - INFLUXDB_DB=db

            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=hello

    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        user: "1000"
        ports:
            - 3000:3000
        volumes:
            - ./gfdata:/var/lib/grafana
        depends_on:
            - influxdb

networks:
  crowdeye-ai-engine_some-net:
    external: true
