version: '3.4'

services:  
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
      - "25826:25826/udp"
    volumes:
      - ./influxdata:/var/lib/influxdb
      - ./config:/etc/influxdb/
    environment:
      - INFLUXDB_DB=db

      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=hello 


  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    user: "1000" 
    ports:
      - 3000:3000
    volumes:
      - ./gfdata:/var/lib/grafana
    depends_on:
      - influxdb