# Generated by Django 3.1.1 on 2020-09-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdeye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.CharField(max_length=4096),
        ),
    ]
