# Generated by Django 3.1.1 on 2020-09-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdeye', '0002_auto_20200923_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='node_id',
            field=models.CharField(default='none-lol', max_length=4096),
            preserve_default=False,
        ),
    ]
