# Generated by Django 3.1.1 on 2020-10-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdeye', '0004_camera_rtl'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='readable_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
